### ISSUE TITLE
Suggest to loosen the dependency on schedule

### ISSUE THREAD

**Issue by Agnes-U** [RafhaanShah/Net-Mon#2]
Hi, your project Net-Mon(commit id: 01d49086a45b6ed2003bc1d8b435ca4711db985e) requires "schedule==0.6.0" in its dependency. After analyzing the source code, we found that the following versions of schedule can also be suitable, i.e., schedule 0.4.3, 0.5.0, 1.0.0, since all functions that you directly (2 APIs: schedule.__init__.every, schedule.__init__.run_pending) or indirectly (propagate to 4 schedule's internal APIs and 0 outsider APIs) used from the package have not been changed in these versions, thus not affecting your usage.

Therefore, we believe that it is quite safe to loose your dependency on schedule from "schedule==0.6.0" to "schedule>=0.4.3,<=1.0.0". This will improve the applicability of Net-Mon and reduce the possibility of any further dependency conflict with other projects. 

May I pull a request to further loosen the dependency on schedule?

By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

**Comment by RafhaanShah** [comment]
Hey thanks for the suggestion! Not looking to make this change at the moment, but I'll keep it in mind for the next release, thanks!
